/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_log_free: (a: number, b: number) => void;
export const __wbg_scorer_free: (a: number, b: number) => void;
export const league_names: () => [number, number];
export const log_datetime: (a: number) => [number, number];
export const log_describe: (a: number, b: number, c: number) => [number, number, number, number];
export const log_export: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const log_fix: (a: number, b: number) => [number, number, number];
export const log_fix_count: (a: number) => number;
export const log_flights: (a: number) => [number, number, number];
export const log_header: (a: number, b: number, c: number) => [number, number, number];
export const log_header_keys: (a: number) => [number, number];
export const log_longest_flight: (a: number) => [number, number, number];
export const log_new: (a: number, b: number) => [number, number, number];
export const log_score: (a: number, b: number, c: number, d: number) => [number, number, number];
export const log_track: (a: number) => [number, number, number];
export const log_track_bytes: (a: number) => [number, number];
export const log_tzn: (a: number) => [number, number];
export const scorer_new: (a: number, b: number) => [number, number, number];
export const scorer_solve: (a: number, b: number, c: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
